import {useEffect,useState} from 'react';
import {stamp} from './Workspace';
export default function ModelReview({session}){
 const [data,setData]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState(''),[filter,setFilter]=useState('review'),[family,setFamily]=useState('all'),[search,setSearch]=useState(''),[page,setPage]=useState(1),[selected,setSelected]=useState(null),[name,setName]=useState(''),[product,setProduct]=useState('cfd'),[articleId,setArticleId]=useState('');
 async function call(body){setBusy(true);setError('');setSuccess('');try{const r=await fetch('/api/model-review',{method:body?'POST':'GET',headers:{'x-app-session':session,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});let d;try{d=await r.json();}catch{throw new Error('Request interrupted. Refresh to inspect saved state before retrying.');}if(!r.ok)throw new Error(d.error);setData(d);if(body){setSuccess(body.action==='scan'?'Full FAQ scan completed.':body.action==='nominate'?'Candidate added for review.':'Model review saved.');if(body.action!=='scan')setSelected(null);}}catch(e){setError(e.message);}finally{setBusy(false);}}
 useEffect(()=>{call();},[session]);
 useEffect(()=>{setPage(1);setSelected(null);},[filter,family,search]);
 useEffect(()=>{if(selected&&window.matchMedia('(max-width:1100px)').matches)document.querySelector('.model-review-detail')?.scrollIntoView({block:'start',behavior:'auto'});},[selected]);
 const models=data?.catalog?.models||[], filtered=models.filter(m=>(filter==='all'||m.status===filter)&&(family==='all'||m.product===family)&&m.name.toLowerCase().includes(search.toLowerCase()));
 const pages=Math.max(1,Math.ceil(filtered.length/10)),current=Math.min(page,pages),visible=filtered.slice((current-1)*10,current*10),active=models.find(m=>m.slug===selected);
 return <div className="settings-stack model-review-page"><section className="settings-card discovery-toolbar"><div className="settings-head"><div><h2>Account model review</h2><p>Review candidates before they appear in scope.</p></div><button className="btn btn-primary" disabled={busy} onClick={()=>call({action:'scan'})}>{busy?'Working…':'Rescan all FAQs'}</button></div><div className="discovery-summary"><b>{models.filter(m=>m.status==='review').length} awaiting review</b><span>{data?.catalog?.articlesScanned??'—'} FAQs checked</span><small>Last scan: {data?stamp(data.scan?.at||data.catalog?.generatedAt):'Loading…'} · {data?.scan?.status||'—'}</small></div>{data?.scan?.error&&<p className="inline-error">{data.scan.error}</p>}{error&&<div className="inline-error" role="alert">{error}<button disabled={busy} onClick={()=>call()}>Refresh saved state</button></div>}{success&&<p className="model-save-feedback" role="status">✓ {success}</p>}</section>
 <div className={'model-review-layout'+(active?' has-selection':'')}><section className="settings-card model-list-card"><div className="model-filters"><input aria-label="Search model names" placeholder="Search models…" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Model status" value={filter} onChange={e=>setFilter(e.target.value)}>{[['review','Awaiting review'],['current','Current'],['previous','Previous'],['rejected','Rejected / hidden'],['all','All statuses']].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><select aria-label="Product family" value={family} onChange={e=>setFamily(e.target.value)}><option value="all">CFD & Futures</option><option value="cfd">CFD</option><option value="futures">Futures</option></select></div><div className="model-list-meta"><span>{filtered.length} matching models</span><span>Page {current} of {pages}</span></div>{visible.map(m=><button key={m.slug} className={'model-list-row'+(selected===m.slug?' selected':'')} onClick={()=>setSelected(m.slug)} aria-pressed={selected===m.slug}><span><b>{m.name}</b><small>{m.product==='futures'?'Futures':'CFD'} · {m.articleCount||0} FAQ articles</small></span><span className={'model-status '+m.status}>{m.status==='review'?'Review':m.status}</span><span aria-hidden="true">›</span></button>)}{!visible.length&&<p className="empty-admin">{busy?'Loading models…':'No models match these filters.'}</p>}<div className="model-pager"><button className="btn btn-secondary" disabled={current===1} onClick={()=>setPage(current-1)}>← Previous</button><span>Page {current} / {pages}</span><button className="btn btn-secondary" disabled={current===pages} onClick={()=>setPage(current+1)}>Next →</button></div></section>
 {active&&<aside className="model-review-detail" aria-label="Selected model review"><div className="model-detail-heading"><b>Selected model</b><button className="btn btn-secondary" onClick={()=>setSelected(null)}>Close ×</button></div><ModelCard key={active.slug+active.name+active.status} model={active} models={models} busy={busy} call={call}/></aside>}</div>
 <details className="settings-card model-nomination"><summary>Can’t find a model? Nominate it from an existing FAQ</summary><p>The scanner checks existing titles and article text, but may miss unfamiliar names. Use a published FAQ ID to add a candidate.</p><form onSubmit={e=>{e.preventDefault();call({action:'nominate',name,product,articleId});}}><label>Model name</label><input required maxLength={120} value={name} onChange={e=>setName(e.target.value)}/><label>Product</label><select value={product} onChange={e=>setProduct(e.target.value)}><option value="cfd">CFD</option><option value="futures">Futures (FUT)</option></select><label>Existing FAQ article ID</label><input required value={articleId} onChange={e=>setArticleId(e.target.value)}/><button className="btn btn-primary" disabled={busy}>Add for review</button></form></details></div>;
}
function ModelCard({model,models,busy,call}){const [name,setName]=useState(model.name),[target,setTarget]=useState('');return <article className="workspace-record"><h3>{model.name}</h3><span className={'model-status '+model.status}>{model.product.toUpperCase()} · {model.status}</span><details><summary>Source evidence · {model.articles?.length||0} articles</summary>{model.articles?.map(a=><div className="model-evidence" key={a.id}><b>{a.title}</b><small>Article ID: {a.id} · {a.location||'catalogue evidence'}</small>{a.excerpt&&<blockquote>{a.excerpt}</blockquote>}{/^https?:\/\//.test(a.url)&&<a href={a.url} target="_blank" rel="noreferrer">Open FAQ ↗</a>}</div>)}</details><label>Display name</label><input aria-label={'Display name for '+model.name} value={name} onChange={e=>setName(e.target.value)} maxLength={120}/><div className="row"><button className="btn btn-primary" disabled={busy||!name.trim()} onClick={()=>call({action:'review',slug:model.slug,name,status:'current'})}>Approve as current</button><button className="btn btn-secondary" disabled={busy||!name.trim()} onClick={()=>call({action:'review',slug:model.slug,name,status:'previous'})}>Mark previous</button><button className="btn btn-danger" disabled={busy} onClick={()=>call({action:'review',slug:model.slug,name,status:'rejected'})}>Reject / hide</button></div><details><summary>Merge a duplicate</summary><select aria-label={'Merge '+model.name+' into'} value={target} onChange={e=>setTarget(e.target.value)}><option value="">Select approved model…</option>{models.filter(m=>m.slug!==model.slug&&m.product===model.product&&['current','previous'].includes(m.status)).map(m=><option key={m.slug} value={m.slug}>{m.name}</option>)}</select><button className="btn btn-secondary" disabled={busy||!target} onClick={()=>call({action:'merge',slug:model.slug,target})}>Merge aliases</button></details></article>;}
