import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';

export function stamp(value) { return value ? new Date(value).toLocaleString('en-GB',{timeZone:'Asia/Dhaka',day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit',second:'2-digit'})+' GMT+6' : 'Not opened'; }
export async function workspaceRequest(session,action,body,params='') {
 const response=await fetch('/api/workspace?action='+action+params,{method:body?'POST':'GET',headers:{'x-app-session':session,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});
 const text=await response.text(); let data;
 try{data=JSON.parse(text);}catch{throw new Error('The server could not complete this request. Try again.');}
 if(!response.ok)throw new Error(data.error||'Request failed');return data;
}

export function WorkspaceSidebar({session,role,onOpen,onNew,busy,refreshKey}) {
 const [view,setView]=useState(''),[items,setItems]=useState([]),[more,setMore]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(''),[unread,setUnread]=useState(0),[opened,setOpened]=useState(null);
 const request=useRef(0),panel=useRef(null);
 async function count(){try{const d=await workspaceRequest(session,'inbox');setUnread(d.unread||0);}catch{}}
 useEffect(()=>{count();const refresh=()=>{if(!document.hidden)count();};const timer=setInterval(refresh,30000);window.addEventListener('focus',refresh);return()=>{clearInterval(timer);window.removeEventListener('focus',refresh);};},[session,refreshKey]);
 async function load(next,offset=0){const sequence=++request.current;setView(next);setLoading(true);setError('');if(!offset){setItems([]);setOpened(null);}try{const d=await workspaceRequest(session,next,null,'&offset='+offset);if(sequence!==request.current)return;setItems(old=>offset?[...old,...d.items]:d.items);setMore(d.more);if(d.unread!==undefined)setUnread(d.unread);}catch(e){if(sequence===request.current)setError(e.message);}finally{if(sequence===request.current)setLoading(false);}}
 async function openMessage(item){setOpened(item.id);if(item.read_at)return;try{const d=await workspaceRequest(session,'read',{id:item.id});setItems(old=>old.map(x=>x.id===item.id?{...x,read_at:d.readAt}:x));count();}catch(e){setError('Message opened, but its read receipt was not saved: '+e.message);}}
 useEffect(()=>{if(view)panel.current?.focus();},[view]);
 return <><aside className="workspace-nav"><Link href="/" className="workspace-wordmark"><span>FN</span><div>FundedNext<small>SUPPORT WORKSPACE</small></div></Link><span className="nav-caption">YOUR WORKSPACE</span><button className={!view?'active':''} disabled={busy} onClick={()=>{setView('');onNew();}}>＋ New conversation</button><button onClick={()=>load('history')}>◷ My conversations</button><button onClick={()=>load('disputes')}>⚑ Submitted disputes</button><button onClick={()=>load('inbox')}>✉ Inbox <b className="nav-count">{unread||''}</b></button><span className="nav-caption">KEEP IN MIND</span><p className="nav-tip">Choose the client’s product and account model before asking. Review the answer and its sources before sharing.</p>{role==='admin'&&<Link className="nav-admin" href="/admin">▦ Admin workspace →</Link>}<small className="nav-bottom">Made for thoughtful support.</small></aside>
 {view&&<div className="workspace-drawer-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setView('')}><section className="workspace-drawer" role="dialog" aria-modal="true" aria-label={view} tabIndex={-1} ref={panel} onKeyDown={e=>{if(e.key==='Escape')setView('');if(e.key==='Tab'){const nodes=panel.current.querySelectorAll('button:not(:disabled),a,input,textarea');if(!nodes.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}}}><header><div><span className="eyebrow">Your workspace</span><h2>{({history:'My conversations',disputes:'Submitted disputes',inbox:'Inbox & notifications'})[view]}</h2></div><button className="btn btn-secondary" onClick={()=>setView('')}>Close ✕</button></header>{error&&<div className="inline-error" role="alert">{error}<button onClick={()=>load(view)}>Retry</button></div>}
 {items.map(item=><article className="workspace-record" key={item.id}>{view==='history'?<><small>{stamp(item.created_at)}</small><h3>{item.question||'Recorded request'}</h3><p>{item.answer.slice(0,220)}{item.answer.length>220?'…':''}</p><button className="btn btn-secondary" disabled={busy} onClick={()=>{onOpen(item);setView('');}}>Open question & answer →</button></>:view==='disputes'?<><span className="state-pill">{item.status==='snippet_generated'?'Approved · correction created':item.status}</span><h3>{item.question}</h3><small>Submitted {stamp(item.created_at)}</small><details><summary>Submission & decision</summary><p>{item.dispute_reason}</p><p className="preserve-text">{item.answer}</p>{item.reviewed_at&&<div className="resolution"><b>Reviewed {stamp(item.reviewed_at)}</b><p>{item.approval_reason}</p></div>}</details></>:<><button className="inbox-subject" onClick={()=>opened===item.id?setOpened(null):openMessage(item)}><span>{!item.read_at&&<i className="unread-dot"/>}{item.title}</span><small>{stamp(item.created_at)} · {item.kind==='dispute'?'Dispute update':'Admin message'}</small></button>{opened===item.id&&<div><p className="preserve-text">{item.body}</p><small>First opened: {stamp(item.read_at)}</small>{item.kind==='dispute'&&<button className="btn btn-secondary" onClick={()=>load('disputes')}>View my disputes</button>}{!item.read_at&&<button onClick={()=>openMessage(item)}>Retry read receipt</button>}</div>}</>}</article>)}
 {loading&&<p role="status">Loading your records…</p>}{!loading&&!items.length&&!error&&<p className="empty-admin">Nothing here yet.</p>}{more&&<button className="btn btn-secondary" disabled={loading} onClick={()=>load(view,items.length)}>Load older records</button>}</section></div>}</>;
}

export function AdminOverview({session,onNavigate}) {
 const [stats,setStats]=useState(null),[error,setError]=useState('');
 useEffect(()=>{let active=true;async function load(){try{const r=await fetch('/api/stats',{headers:{'x-app-session':session}});const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not load the overview');if(active){setStats(d);setError('');}}catch(e){if(active)setError(e.message);}}load();const timer=setInterval(load,60000);return()=>{active=false;clearInterval(timer);};},[session]);
 return <div className="settings-stack"><section className="overview-welcome"><span className="eyebrow">Workspace overview</span><h2>A clearer view of your team’s knowledge.</h2><p>Keep information current, review concerns, and help your team work confidently.</p></section>{error&&<div className="inline-error">{error}</div>}<div className="overview-stats">{[['Published FAQs',stats?.totalArticles],['Searchable passages',stats?.totalChunks],['Queued articles',stats?.queuedArticles],['Pending disputes',stats?.pendingDisputes]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value?.toLocaleString()??'—'}</strong></div>)}</div><section className="settings-card"><h2>Where would you like to start?</h2><div className="overview-actions">{[['modelreview','◎','Review account models','Find missed names in existing FAQs and review discovery candidates.'],['disputes','⚑','Review disputed answers','Investigate concerns and communicate a decision.'],['messages','✉','Message your team','Send an update and check first-open reports.'],['querylogs','◷','Explore conversations','Review questions, answers, and recorded evidence.']].map(([id,icon,title,text])=><button key={id} onClick={()=>onNavigate(id)}><span>{icon}</span><b>{title} →</b><small>{text}</small></button>)}</div></section><section className="settings-card"><h2>Latest knowledge coverage</h2><div className="overview-actions"><article><span className="eyebrow">Latest FAQ synced</span><h3>{stats?.latestFaq?.title||'No completed sync recorded'}</h3><small>{stamp(stats?.latestFaq?.last_indexed_at)}</small></article><article><span className="eyebrow">Latest CEx Notice covered</span><h3>{stats?.latestNotice?.title||'No Notice recorded'}</h3><small>{stats?.latestNotice?.posted_at?stamp(stats.latestNotice.posted_at):'—'}</small></article></div></section></div>;
}

export function AdminMessages({session}) {
 const [title,setTitle]=useState(''),[body,setBody]=useState(''),[audience,setAudience]=useState('all'),[items,setItems]=useState([]),[receipts,setReceipts]=useState([]),[selected,setSelected]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[more,setMore]=useState(false),[moreReport,setMoreReport]=useState(false),[success,setSuccess]=useState('');const id=useRef(null);
 async function load(offset=0){try{const d=await workspaceRequest(session,'sent',null,'&offset='+offset);setItems(old=>offset?[...old,...d.items]:d.items);setMore(d.more);}catch(e){setError(e.message);}}
 useEffect(()=>{load();},[session]);
 async function report(message,offset=0){setError('');setSelected(message);try{const d=await workspaceRequest(session,'report',null,'&id='+message.id+'&offset='+offset);setReceipts(old=>offset?[...old,...d.items]:d.items);setMoreReport(d.more);}catch(e){setError(e.message);}}
 async function send(e){e.preventDefault();if(!window.confirm(audience==='all'?'Send this message to every registered workspace user?':`Send this message to ${audience}?`))return;setBusy(true);setError('');setSuccess('');try{id.current ||= crypto.randomUUID();await workspaceRequest(session,'send',{id:id.current,title,body,audience});id.current=null;setTitle('');setBody('');setSuccess('Message sent and delivery records saved.');load();}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <div className="settings-stack"><section className="settings-card"><h2>A direct line to your team.</h2><p>Messages stay in each recipient’s inbox. “All” includes registered users at send time. Open receipts record the first server-confirmed opening, not proof of reading or understanding.</p>{error&&<div className="inline-error" role="alert">{error}</div>}{success&&<p role="status">{success}</p>}<form onSubmit={send}><label>Recipient email, or all</label><input required value={audience} onChange={e=>{setAudience(e.target.value);id.current=null;}} disabled={busy}/><label>Subject</label><input required maxLength={160} value={title} onChange={e=>{setTitle(e.target.value);id.current=null;}} disabled={busy}/><label>Message</label><textarea required maxLength={12000} rows={6} value={body} onChange={e=>{setBody(e.target.value);id.current=null;}} disabled={busy}/><button className="btn btn-primary" disabled={busy}>{busy?'Sending…':'Send message'}</button></form></section><section className="settings-card"><div className="settings-head"><h2>Sent messages & opening reports</h2><button className="btn btn-secondary" onClick={()=>{load();if(selected)report(selected);}}>Refresh reports</button></div>{items.map(x=><article className="workspace-record" key={x.id}><h3>{x.title}</h3><small>{stamp(x.created_at)} · {x.audience} · sent by {x.sender}</small><p className="preserve-text">{x.body}</p><button className="btn btn-secondary" onClick={()=>report(x)}>View recipient report →</button></article>)}{more&&<button onClick={()=>load(items.length)}>Older messages</button>}{!items.length&&<p>No sent messages yet.</p>}</section>{selected&&<section className="settings-card"><h2>Opening report: {selected.title}</h2><p>Times are GMT+6. Refresh to see newly opened messages.</p>{receipts.map(r=><div className="receipt-row" key={r.id}><b>{r.recipient}</b><span>{r.read_at?'First opened '+stamp(r.read_at):'Not opened'}</span></div>)}{moreReport&&<button onClick={()=>report(selected,receipts.length)}>More recipients</button>}</section>}</div>;
}

const scopeSteps=[['.scope-bar','Start with the right scope','Scope limits which knowledge the assistant can use. An answer outside the selected product or model may be incomplete. Check it against the client’s account.'],['.scope-bar .app-select','CFD, FUT, or both','Choose CFD for CFD accounts or Futures (FUT) for futures accounts. Both searches the two product families when your question genuinely needs both.'],['.scope-model','Choose the account model','Select the exact model when known. All models searches the selected family. Use Set as my default to remember your usual choice; one-off choices return to that default after an answer.']];
const answerSteps=[['.assistant-message:last-of-type .answer-actions','Review, copy, and give feedback','Copy answer copies plain text. Helpful and Great answer are optional positive ratings. Review the account model and source passages before sending anything to a client.'],['.assistant-message:last-of-type .answer-actions button:last-child','Spot a problem? Submit a dispute','Dispute answer records what is wrong or missing for Admin review. Explain the specific concern. Track the decision in Submitted disputes and your notifications.'],['.assistant-message:last-of-type .sources','Check the evidence','Expand the sources to inspect the exact passages. A source link is not a guarantee that every claim is supported. You remain responsible for reviewing the answer.']];
export function WorkspaceTour({session,blocked,hasAnswer}) {
 const [person,setPerson]=useState(null),[step,setStep]=useState(0),[error,setError]=useState(''),[saving,setSaving]=useState(false),[box,setBox]=useState(null);const next=useRef(null);
 async function load(){try{setPerson((await workspaceRequest(session,'tour')).person);setError('');}catch(e){setError(e.message);}}
 useEffect(()=>{load();},[session]);
 const stage=person&&!person.scope_tour_at?'scope':person&&!person.answer_tour_at&&hasAnswer?'answer':null;
 const steps=stage==='scope'?scopeSteps:answerSteps;
 useEffect(()=>{if(!stage||blocked)return;const target=document.querySelector(steps[step][0])||document.querySelector('.composer-wrap');target?.scrollIntoView({block:'center',behavior:'instant'});const measure=()=>{const r=target?.getBoundingClientRect();if(r)setBox({top:r.top-5,left:r.left-5,width:r.width+10,height:r.height+10});};measure();window.addEventListener('resize',measure);window.addEventListener('scroll',measure,true);next.current?.focus();return()=>{window.removeEventListener('resize',measure);window.removeEventListener('scroll',measure,true);};},[stage,step,blocked]);
 if(blocked||(!stage&&!error))return null;
 async function advance(){if(step<steps.length-1){setStep(step+1);return;}setSaving(true);try{await workspaceRequest(session,'tour',{stage});setPerson(p=>({...p,[stage+'_tour_at']:new Date().toISOString()}));setStep(0);setError('');}catch(e){setError(e.message);}finally{setSaving(false);}}
 return <div className="tour-layer">{box&&stage&&<div className="tour-spotlight" style={box}/>}<section className="tour-card" role="dialog" aria-modal="true" aria-labelledby="tour-title" onKeyDown={e=>{if(e.key==='Tab'){e.preventDefault();next.current?.focus();}}}><span className="eyebrow">Quick workspace guide · {step+1} / 3</span><h2 id="tour-title">{stage?steps[step][1]:'Guide unavailable'}</h2><p>{stage?steps[step][2]:'Please retry so your introduction can be loaded.'}</p>{error&&<div className="inline-error">{error}</div>}<button ref={next} className="btn btn-primary" disabled={saving} onClick={stage?advance:load}>{saving?'Saving…':step===2?'Got it — continue':'Next →'}</button></section></div>;
}
